name: Node CI

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8, 10, 12]

    steps:
    - uses: starlingbank/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: starlingbank/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build
        npm test
      env:
        CI: true
